# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c74baa8ddb3cee88d03cf72ef8ea5decd6e43452bea3c68d2feb64b0e49ec888015940b8d55e3b2adcb66615b024bfe5249576d8ab6df95059286de24a6a68f

test:
  secret_key_base: 484429ae96bb1b6832668533e993fbbe7a2a04847385662fee9f9bf951bca74cf37dd8462dc77af296cf456cb1b50609baa616b671e6256ef97c9dae4488dceb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
